### ISSUE TITLE
Build Reusable chat bubble Components

### ISSUE THREAD

**Issue by AnanyaPappula** [VedaVerse-opensource/chatsphere#8]
Create reusable UI component for chat bubbles This components should be designed to be flexible and easily integrated into various parts of the application.

**Details:**

- **Chat Bubbles:** Design components for both sent and received messages.
- **TailwindCSS:** Style components using TailwindCSS for consistency.
- **Reference:** Use the [[Figma design](https://www.figma.com/design/6x6jrOQgfMoWWENXD9NFF0/ChatSphere?node-id=0-1&t=mNiBIXIcFv7HStX0-1)](https://www.figma.com/design/6x6jrOQgfMoWWENXD9NFF0/ChatSphere?node-id=0-1&t=mNiBIXIcFv7HStX0-1) for component layout and styling.

**Acceptance Criteria:**

- Components are reusable and customizable.
- Components are well-documented and easy to integrate.

**Comment by sumirx** [comment]
Completed, Closing
